@include('form.input', ['input' => 'cpf', 'attributes' => ['placeholder' => 'CPF']])
@include('form.input', ['input' => 'name', 'attributes' => ['placeholder' => 'Nome']])
@include('form.input', ['input' => 'phone', 'attributes' => ['placeholder' => 'Telefone']])
@include('form.input', ['input' => 'email', 'attributes' => ['placeholder' => 'E-mail']])
@include('form.password', ['input' => 'password', 'attributes' => ['placeholder' => 'Senha']])
